remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
aux_links:
    "University's website":
      - "//docbnmu.ac.in"
title: University Department of Chemistry
description: Bhupendra Narayan Mandal University

