remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
aux_links:
    "University's website":
      - "//docbnmu.ac.in"
title: Univ. Dept. of Chemistry
metatitle: University Department of Chemistry.
description: Bhupendra Narayan Mandal University

